name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Show Terraform Version
        run: terraform --version

      - name: Validate module
        run: |
          terraform init
          terraform validate
        working-directory: test
